# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-20 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='user_ratings',
            field=models.ManyToManyField(related_name='rated_shows', to='app.User'),
        ),
    ]
